//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafLegacyNightmare.Module.BusinessObjects.NWind
{

    [Persistent(@"CustomerCustomerDemo")]
    public partial class Customercustomerdemo : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Size(5)]
            [Persistent("CustomerID")]
            public string CustomerID { get; set; }
            [Size(10)]
            [Persistent("CustomerTypeID")]
            public string CustomerTypeID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
        public Customercustomerdemo(Session session) : base(session) { }
    }

}
