//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XafLegacyNightmare.Module.BusinessObjects.NWind
{

    [Persistent(@"EmployeeTerritories")]
    public partial class Employeeterritories : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Persistent("EmployeeID")]
            public int EmployeeID { get; set; }
            [Size(20)]
            [Persistent("TerritoryID")]
            public string TerritoryID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
        public Employeeterritories(Session session) : base(session) { }
    }

}
